### ISSUE TITLE
Make an STL mesh watertight/closed

### ISSUE THREAD

**Issue by tomathew** [MeshInspector/MeshInspector#133]
Hello,

I have an STL mesh file with multiple regions (per se). I am attaching the files here as well. I think because of the self-intersecting facets/points from multiple regions, the mesh is not manifold/closed.  I tried your software with "Mesh Inspector" and "Mesh Healer" utilities, but not quite sure how to achieve my goal of making my STL file closed. Is it possible with your software? Also, would like some help with exporting the STL files as STEP/IGES, whether if it's possible.

Best,
Tom
Attached files: [Geometry.zip](https://github.com/MeshInspector/MeshInspector/files/13380879/Geometry.zip)

**Comment by Fedr** [comment]
Hello Tom,

Yes, you can use MeshInspector to make your objects manifold/closed.

Mesh Healer is perfrect tool for that. It is a distructive tool in a way that it completely recreate the mesh with the precision depending on the voxel size, and you might get too many triangles in the result with small voxel size. So the recomendation to use Decimate tool after Mesh Healer to receive mesh with small number of elements. Please find Alcoa.stl in [Fixed.zip](https://github.com/MeshInspector/MeshInspector/files/13382960/Fixed.zip)

The other option is to use Fill Holes in Triangulate Only mode:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/d51dab0f-fa86-4939-ab3e-c485530d606d)

It works well for the other your model - GEBracket.stl. 

Please let us know whether fixed models are ok for you.

Best regards,
Fedor

**Comment by tomathew** [comment]
Hello,

Thank you for your prompt response. I was in Linux VM on Windows without the Nvidia capability. When tried on the Windows version the Mesh healing completed successfully. 

I was wondering if there is also a way to keep the regions (force, support, none) in the original STL file in the output STL as well.

I also tried manually doing it as three separate STL files, but couldn't make all manifold ones.

Thanks,
Tom

**Comment by Fedr** [comment]
Hello,

> Thank you for your prompt response. I was in Linux VM on Windows without the Nvidia capability. When tried on the Windows version the Mesh healing completed successfully.

It is strange, because without Nvidia card we expect MeshInspector to work, but somewhat slower. Did you see some error message on Linux VM or the result was different (if so please attach it for our considiration)?

> I was wondering if there is also a way to keep the regions (force, support, none) in the original STL file in the output STL as well. I also tried manually doing it as three separate STL files, but couldn't make all manifold ones.

Could you please clarify what result you would like to receive here? Probably an example result made in some other software can be of much help here.

For example you first file contains 4 components:

![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/2a5abc2f-35b1-4eb5-ad6e-163734afbadd)

If we convert each of them in a closed one, then the whole object will be very different.

Best regards,
Fedor

**Comment by Fedr** [comment]
Hello,

Thanks for the image with the error.
1. Is "Enable CUDA" option turned on when the error happens? 
2. And does the error disappear if you uncheck the option?
3. Could you please send us the image of Home/About/System Information for the system where the error takes place?

The screenshots similar to Gmsh can be taken if after opening your initial Alcoa.stl
1. Click Mesh/Components:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/8363c7b2-fe3a-4a51-886a-9f2354da3d65)
The object will split on 4.

2. In the context menu select Edges and unselect Faces:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/2c887c1b-ef61-4a26-8e6d-9b465bc61ae0)

3. If change edge color for different components you will get a similar screenshot:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/595b82cc-84f9-4199-ace8-cc766a067d11)

The only difference is that your screenshots contain 6 components and I see in MeshInspector only 4 components. Can it be that you sent initially one STL file and open in Gmsh another one?

4. You can try Fill Holes with every component. Is it what you expect?
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/529b73b2-c760-4105-a74e-85379797cac9)

Best regards,
Fedor

**Comment by tomathew** [comment]
Hello,

This error happens on Ubuntu22 on a virtual machine (VMware workstation on Windows). As it doesn't have Nvidia in the virtual machine (it has a different video card, as it is a virtual machine); the Enable CUDA option is inactive on Ubuntu OS. See the attached image.
![Screenshot from 2023-11-17 20-05-04](https://github.com/MeshInspector/MeshInspector/assets/22793567/53afc43f-df72-4b82-8d65-2afd7d38b112)

My intention in showing the Gmsh screenshot was just to enquire about the possibility of maintaining the Physical regions as it is in the input STL file. After mesh healing the physical regions are lost in the output file.

It doesn't matter if my requirement can't be met. My intention in using this platform is to make the STL geometry watertight/closed/manifold for creating volume mesh in Gmsh for FEA. Although the meshInspector successfully healed the mesh to a closed manifold, all the region attributes of the mesh faces were lost in the output STL. I need this for the finite element solver to identify support and load faces to apply boundary conditions.

Filling the holes and closing them for the support region is not possible, as I have to apply boundary conditions.

I think I will contact you soon for a custom code development, and then we can discuss my requirements in detail on a meeting. 

Let me know if you need more information.

Kind regards and Thanks,
Tom Mathew

**Comment by tomathew** [comment]
Hello,

I have simplified my concern here. I am attaching the STL files of the components which are non-manifold causing problems for volumetric meshing in Gmsh. Can you help me fix/heal these individual component STL files to watertight meshes? I have to keep the boundaries as it is, and I can't close the boundaries with a hole-filling feature. I can't close the ends of these STL files with a disc at the ends. I hope you understand my concern. 

Can you help me make these individual STL files a manifold/watertight one? When I try the mesh healing here on my PC with the maximum possible voxel, the entire mesh disappears (no faces/face count becomes 0). It will be great to see what can be the fix here for these with your platform.

[non-manifold.zip](https://github.com/MeshInspector/MeshInspector/files/13399141/non-manifold.zip)

**Comment by Fedr** [comment]
Hello,

Actually I am bit confused, because manifold/watertight mesh means that it does not have any boundaries at all, so all of them must be closed/filled somehow.

In your input 'force' model there are 6 boundaries (in red):
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/96b2697e-6ed4-4dd9-961a-028fd5e1b289)

So I closed 4 of them, leaving the outer 2:
![image](https://github.com/MeshInspector/MeshInspector/assets/3136125/7dcfce3d-e5de-4c33-a4eb-ab9359f10473)
The model itself:
[force-fixed.stl.zip](https://github.com/MeshInspector/MeshInspector/files/13401178/force-fixed.stl.zip)

If it is not what you are looking for, could you please send an expected result or draw it somehow?

Best regards,
Fedor

**Comment by justAPhDStudent** [comment]
Hello,
First of all, a great thanks for your time for helping me out on this. The error Gmsh (volumetric mesher) gave me when tetrahedralizing/meshing was self-intersecting facets which meant open/non-manifold geometries. So, when I tried making the STL file manifold, it solved the problem in some cases. But in some cases with different physical regions, it persisted. That's why I tried the route of exploring to make individual components a closed/manifold one to avoid self-intersections.

It didn't help. I guess I have to follow a different route.
I'll reach out to you in future personally with a custom code development.

Thanks again for your time.
I guess you can close this issue as well.

Best regards,
Tom

**Comment by tomathew** [comment]
Hello,

First of all, a great thanks for your time for helping me out on this. The error Gmsh (volumetric mesher) gave me when tetrahedralizing/meshing was self-intersecting facets which meant open/non-manifold geometries. So, when I tried making the STL file manifold, it solved the problem in some cases. But in some cases with different physical regions, it persisted. That's why I tried the route of exploring to make individual components a closed/manifold one to avoid self-intersections.

It didn't help. I guess I have to follow a different route.
I'll reach out to you in future personally with a custom code development.

Thanks again for your time. I guess you can close this issue as well.

Best regards,
Tom

**Comment by Fedr** [comment]
Probably you expect to get something like this?
[Watertight.ply.zip](https://github.com/MeshInspector/MeshInspector/files/13402474/Watertight.ply.zip)

**Comment by tomathew** [comment]
I will contact you soon with my requirement. 
Thanks!
